[theme]

# Base dark mode
base = "dark"

# A klar men dempet blå som aksentfarge (knapper, sliders etc.)
primaryColor = "#4EA8DE"

# Hovedbakgrunn: nesten svart (gir fokus på plots og tekst)
backgroundColor = "#0E1117"

# Sekundær bakgrunn: litt lysere grå for paneler og widgets
secondaryBackgroundColor = "#1E222B"

# Tekstfarge: lett lesbar lys grå
textColor = "#E1E1E6"

# Lenker: en frisk cyan, som gir kontrast uten å ta over
linkColor = "#4FD1C5"
linkUnderline = false

# Kodebakgrunn: mørk grå (så kodeblokker ikke stjeler fokus)
codeBackgroundColor = "#2D333B"
