[theme]

# Base dark mode
base = "dark"

# A klar men dempet blå som aksentfarge (knapper, sliders etc.)
primaryColor = "#3AE8D6"

# Hovedbakgrunn: nesten svart (gir fokus på plots og tekst)
backgroundColor = "#1C202D"

# Sekundær bakgrunn: litt lysere grå for paneler og widgets
secondaryBackgroundColor = "#152E39"

# Tekstfarge: lett lesbar lys grå
textColor = "#CBCBCB"

# Lenker: en frisk cyan, som gir kontrast uten å ta over
linkColor = "#4FD1C5"
linkUnderline = false

# Kodebakgrunn: mørk grå (så kodeblokker ikke stjeler fokus)
codeBackgroundColor = "#2D333B"
